ServerName store.mochios.org

<VirtualHost *:80>
    ServerName store.mochios.org

    DocumentRoot /var/www/html/src/public
    DirectoryIndex index.php index.html

    <Directory /var/www/html/src/public>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:80>
    ServerName console.mochios.org

    DocumentRoot /var/www/html/src/public/console
    DirectoryIndex index.php index.html

    <Directory /var/www/html/src/public/console>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:80>
    ServerName api.mochios.org

    DocumentRoot /var/www/html/src/api
    DirectoryIndex index.php

    <Directory /var/www/html/src/api>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>