ServerName mochios.org

<VirtualHost *:80>
    ServerName mochios.org
    ServerAlias www.mochios.org

    DocumentRoot /var/www/html/public

    DirectoryIndex index.php index.html

    <Directory /var/www/html/public>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/appstore_error.log
    CustomLog ${APACHE_LOG_DIR}/appstore_access.log combined
</VirtualHost>

<VirtualHost *:80>
    ServerName console.mochios.org

    DocumentRoot /var/www/html/public/console

    DirectoryIndex index.php index.html

    <Directory /var/www/html/public/console>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/console_error.log
    CustomLog ${APACHE_LOG_DIR}/console_access.log combined
</VirtualHost>